<?php

return [
    [
        'name'    => 'sitename',
        'title'   => '站点名称',
        'type'    => 'string',
        'content' => [],
        'value'   => '商城网站',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'icpbeian',
        'title'   => 'ICP备案号',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'gwabeian',
        'title'   => '公安备案号',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'sitelogo',
        'title'   => '站点Logo',
        'type'    => 'image',
        'content' => [],
        'value'   => '/assets/addons/shop/img/logo.png',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'title',
        'title'   => '首页标题',
        'type'    => 'string',
        'content' => [],
        'value'   => '首页标题',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'keywords',
        'title'   => '首页关键字',
        'type'    => 'string',
        'content' => [],
        'value'   => '首页关键字',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'description',
        'title'   => '首页描述',
        'type'    => 'string',
        'content' => [],
        'value'   => '首页描述',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'theme',
        'title'   => '皮肤',
        'type'    => 'string',
        'content' => [],
        'value'   => 'default',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '仅适用于PC版',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'qrcode',
        'title'   => '公众号二维码',
        'type'    => 'image',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'default_goods_img',
        'title'   => '商品默认图片',
        'type'    => 'image',
        'content' => [],
        'value'   => '/assets/addons/shop/img/noimage.jpg',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'default_category_img',
        'title'   => '分类默认图片',
        'type'    => 'image',
        'content' => [],
        'value'   => '/assets/addons/shop/img/noimage.jpg',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'default_block_img',
        'title'   => '区块默认图片',
        'type'    => 'image',
        'content' => [],
        'value'   => '/assets/addons/shop/img/noimage.jpg',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'default_page_img',
        'title'   => '单页默认图片',
        'type'    => 'image',
        'content' => [],
        'value'   => '/assets/addons/shop/img/noimage.jpg',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'openedsite',
        'title'   => '站点前台开关',
        'type'    => 'checkbox',
        'content' => [
            'pc'     => 'PC',
            'uniapp' => 'Uniapp',
        ],
        'value'   => 'pc,uniapp',
        'rule'    => '',
        'msg'     => '',
        'tip'     => 'PC为网页端，Uniapp仅针对Uniapp版本',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'domain',
        'title'   => '绑定二级域名前缀',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'rewrite',
        'title'   => '伪静态',
        'type'    => 'array',
        'content' => [],
        'value'   => [
            'index/index'    => '/shop/$',
            'goods/index'    => '/shop/a/[:id]',
            'page/index'     => '/shop/p/[:diyname]',
            'search/index'   => '/shop/s',
            'category/index' => '/shop/c/[:diyname]',
            'coupon/show'    => '/shop/coupon/[:coupon]',
            'coupon/index'   => '/shop/coupon',
            'exchange/show'  => '/shop/exchange/[:id]',
            'exchange/index' => '/shop/exchange'
        ],
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '如果需要将简单商城绑定到网站首页，请移除<code>值</code>中的<code>/shop</code>',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'audittype',
        'title'   => '审核方式',
        'type'    => 'radio',
        'content' => [
            'local'    => '本地',
            'baiduyun' => '百度云',
        ],
        'value'   => 'local',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '如果启用百度云，请输入百度云AI平台应用的AK和SK，预留暂未使用',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'nlptype',
        'title'   => '分词方式',
        'type'    => 'radio',
        'content' => [
            'local'    => '本地',
            'baiduyun' => '百度云',
        ],
        'value'   => 'local',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '如果启用百度云，请输入百度云AI平台应用的AK和SK',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'aip_appid',
        'title'   => '百度AI平台应用Appid',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '百度云AI开放平台应用AppId',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'aip_apikey',
        'title'   => '百度AI平台应用Apikey',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '百度云AI开放平台应用ApiKey',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'aip_secretkey',
        'title'   => '百度AI平台应用Secretkey',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '百度云AI开放平台应用Secretkey',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'phone',
        'title'   => '客服联系电话',
        'type'    => 'string',
        'content' => [],
        'value'   => '13000000000',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '用户联系客服的电话',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'paytypelist',
        'title'   => '支付方式',
        'type'    => 'checkbox',
        'content' => [
            'wechat' => '微信支付',
            'alipay' => '支付宝支付',
        ],
        'value'   => 'wechat,alipay',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'defaultpaytype',
        'title'   => '默认支付方式',
        'type'    => 'radio',
        'content' => [
            'wechat' => '微信支付',
            'alipay' => '支付宝支付',
        ],
        'value'   => 'wechat',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'money_score',
        'title'   => '订单积分',
        'type'    => 'number',
        'content' => [],
        'value'   => '1',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '订单完成赠送积分，每订单金额一元赠送多少积分',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'comment_score',
        'title'   => '评价积分',
        'type'    => 'number',
        'content' => [],
        'value'   => '1',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '评价赠送积分',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'order_timeout',
        'title'   => '订单超时时长',
        'type'    => 'number',
        'content' => [],
        'value'   => '3600',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '超时订单将自动关闭，单位秒',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'auto_delivery_time',
        'title'   => '订单自动收货时长',
        'type'    => 'number',
        'content' => [],
        'value'   => '3',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '发货订单多少天后自动收货，单位天',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'order_refund_sync',
        'title'   => '订单同步退款',
        'type'    => 'radio',
        'content' => [
            1 => '是',
            0 => '否',
        ],
        'value'   => '1',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '关闭后需前往微信支付宝进行手动退款',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'sendnoticemode',
        'title'   => '通知推送模式',
        'type'    => 'radio',
        'content' => [
            'disabled' => '关闭推送',
            'async'    => '异步并发推送',
            'queue'    => '使用队列推送(需安装队列插件+Redis)',
        ],
        'value'   => 'disabled',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'shippingfeecoupon',
        'title'   => '优惠券适用于运费',
        'type'    => 'radio',
        'content' => [
            '1' => '是',
            '0' => '否',
        ],
        'value'   => '0',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '判断优惠券是否适用于运费',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'shippingfeerefund',
        'title'   => '退款时退运费模式',
        'type'    => 'radio',
        'content' => [
            'averagegoods' => '运费平分至每个商品',
            'lastrefund'   => '运费叠加至最后一个退款商品',
        ],
        'value'   => 'averagegoods',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'category_mode',
        'title'   => '前端分类展示模式',
        'type'    => 'radio',
        'content' => [
            1 => '一级分类',
            0 => '二级分类',
            2 => '三级分类',
        ],
        'value'   => '1',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '目前仅用于uniapp端分类展示',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'autolinks',
        'title'   => '关键字链接',
        'type'    => 'array',
        'content' => [],
        'value'   => [],
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '对应的关键字将会自动加上链接',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'usersidenav',
        'title'   => '会员中心边栏模块',
        'type'    => 'checkbox',
        'content' => [
            'order'    => '我的订单',
            'address'  => '我的收货地址',
            'collect'  => '我的收藏',
            'comment'  => '我的评价',
            'coupon'   => '我的优惠券',
            'exchange' => '我的积分兑换'
        ],
        'value'   => 'order,address,collect,comment,coupon,exchange',
        'rule'    => '',
        'msg'     => '',
        'tip'     => 'PC端会员中心边栏模块',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'cachelifetime',
        'title'   => '缓存默认时长',
        'type'    => 'string',
        'content' => [],
        'value'   => 'true',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '0表示不缓存,具体数字表示缓存时长,true表示永久缓存',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'flagtype',
        'title'   => '标志字典',
        'type'    => 'array',
        'content' => [],
        'value'   => [
            'hot'       => '热门',
            'new'       => '新',
            'recommend' => '推荐',
            'top'       => '置顶',
        ],
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'urlsuffix',
        'title'   => 'URL后缀',
        'type'    => 'string',
        'content' => [],
        'value'   => 'html',
        'rule'    => '',
        'msg'     => '如果不需要后缀可以设置为空',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'moduleurlsuffix',
        'title'   => '模块URL后缀',
        'type'    => 'array',
        'content' => [],
        'value'   => [
            'category' => 'html',
            'goods'    => 'html',
            'page'     => 'html',
            'coupon'   => 'html',
            'exchange' => 'html'
        ],
        'rule'    => '',
        'msg'     => '如果不需要后缀可以设置为空',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'api_mode',
        'title'   => '快递对接方式',
        'type'    => 'radio',
        'content' => [
            'online'  => '正式环境',
            'sandbox' => '沙箱环境',
        ],
        'value'   => 'online',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'EBusinessID',
        'title'   => '快递鸟ID',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'kdNiaoApiKey',
        'title'   => '快递鸟ApiKey',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'printtype',
        'title'   => '打印类型',
        'type'    => 'radio',
        'content' => [
            'system' => '系统自带打印',
            'clodop' => '使用C-Lodop打印(需安装软件)',
        ],
        'value'   => 'system',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'clodop_ip_port',
        'title'   => '打印服务IP+端口',
        'type'    => 'string',
        'content' => [],
        'value'   => 'http://localhost:8000',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'clodop_print_view',
        'title'   => '打印预览/设计',
        'type'    => 'radio',
        'content' => [
            0 => '直接打印',
            1 => '开启预览',
            2 => '预览并设计',
        ],
        'value'   => '1',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'coupon_key',
        'title'   => '优惠券ID加密的key',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '用于优惠券ID的加密，为空时将使用Token的加密Key',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'logisticstype',
        'title'   => '物流查询方式',
        'type'    => 'radio',
        'content' => [
            'kdnapi' => '快递鸟api',
            'kd100'  => '跳转快递100',
        ],
        'value'   => 'kd100',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'freightitemfee',
        'title'   => '满足多运费条件计算方式',
        'type'    => 'radio',
        'content' => [
            'max' => '取最高运费',
            'min' => '取最低运费',
        ],
        'value'   => 'max',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '当满足多个运费条件时，运费计算的方式',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'amap_webapi_key',
        'title'   => '高德地图Web服务API密钥',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '高德地图Web服务API密钥',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'autoredirectmobile',
        'title'   => '移动H5自动重定向',
        'type'    => 'radio',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value'   => '0',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '当部署了Uniapp-H5，用于移动端H5访问时自动重定向',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'mobileurl',
        'title'   => 'H5站点URL',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '如果未部署Uni-APP的H5则无需设置,需http://开头',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'porfilePrompt',
        'title'   => '昵称修改通知频率',
        'type'    => 'radio',
        'content' => [
            'disabled'   => '关闭提示',
            'firstlogin' => '首次登录提示',
            'everylogin' => '每次登录提示',
        ],
        'value'   => 'everylogin',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'notice',
        'title'   => 'Uniapp端公告',
        'type'    => 'array',
        'content' => [],
        'value'   => [
            [
                'title' => '这是一条公告信息',
                'path'  => '/pages/my/my',
            ],
        ],
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'wxapp',
        'title'   => '微信小程序二维码',
        'type'    => 'image',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'wx_appid',
        'title'   => '微信小程序AppID',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '微信小程序的app_id',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'wx_app_secret',
        'title'   => '微信小程序AppSecret',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '微信小程序的app_secret',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'mp_appid',
        'title'   => '微信公众号AppID',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'mp_app_secret',
        'title'   => '微信公众号AppSecret',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'app_id',
        'title'   => 'APP的AppID',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '微信开放平台中应用的Appid，仅Uniapp版本使用',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'app_secret',
        'title'   => 'APP的AppSecret',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '微信开放平台中应用的AppSecret，仅Uniapp版本使用',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'logintypelist',
        'title'   => '登录类型列表',
        'type'    => 'checkbox',
        'content' => [
            'account'      => '账号密码登录',
            'mobile'       => '手机号登录',
            'wechat'       => '微信授权登录',
            'wechatmobile' => '微信手机授权登录',
        ],
        'value'   => 'account,mobile,wechat,wechatmobile',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'wechatautocreate',
        'title'   => '微信登录自动创建账号',
        'type'    => 'radio',
        'content' => [
            1 => '是',
            0 => '否',
        ],
        'value'   => '0',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '首次使用微信登录时是否自动创建账号',
        'ok'      => '',
        'extend'  => '',
    ],
];
