<?php
namespace app\api\controller\xiluxc;


use addons\xiluxc\library\Wechat;
use addons\xiluxc\library\Upload;
use app\common\controller\xiluxc\XiluxcApi;
use app\common\library\Sms;
use app\common\model\xiluxc\activity\UserCoupon;
use app\common\model\xiluxc\brand\BrandUser;
use app\common\model\xiluxc\brand\Shop;
use app\common\model\xiluxc\brand\ShopAccount;
use app\common\model\xiluxc\brand\ShopBrand;
use app\common\model\xiluxc\brand\ShopProperty;
use app\common\model\xiluxc\brand\ShopService;
use app\common\model\xiluxc\brand\ShopVerifier;
use app\common\model\xiluxc\current\Area;
use app\common\model\xiluxc\current\Config;
use app\common\model\xiluxc\brand\Shopvip;
use app\common\model\xiluxc\Divide;
use app\common\model\xiluxc\message\Advice;
use app\common\model\xiluxc\MoneyLog;
use app\common\model\xiluxc\ScoreLog;
use app\common\model\MoneyLog as UserMoneyLog;
use app\common\model\ScoreLog as UserScoreLog;
use app\common\model\xiluxc\user\Third;
use app\common\model\xiluxc\user\UserAccount;
use app\common\model\xiluxc\user\UserPackage;
use app\common\model\xiluxc\user\UserShopAccount;
use app\common\model\xiluxc\finance\Withdraw;
use app\common\validate\xiluxc\brand\UserBrand;
use fast\Random;
use think\Cookie;
use think\Db;
use think\Exception;
use think\exception\PDOException;
use think\exception\ThrowableError;
use think\Hook;
use think\Session;
use think\Validate;
use function fast\array_get;

/**
 * 用户模块控制器
 */
class User extends XiluxcApi
{
    protected $noNeedLogin = ['wxlogin','get_mobile','mobilelogin','auth','auth_back','wechat_public_login'];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 微信登录
     * @ApiParams (name="code", type="string", required=true, description="微信登录code")
     * @ApiParams (name="platform", type="string", required=true, description="登录平台")
     */
        public function wxlogin()
        {
            $param = $this->request->only(['code','platform'],"POST");
            $platform = array_get($param,'platform','wxmini');
            $wechat = new Wechat($platform);
            try {
                switch ($platform){
                    case 'wxmini':
                        $config = Config::getMyConfig('wxmini');
                        if(!$config || !$config['wxmini_appid'] || !$config['wxmini_appid']){
                            throw new Exception("请正确配置微信信息");
                        }
                        $data = $wechat->wxlogin($param['code']);
    
                        $third = Third::where('platform',$platform)->where('openid',$data['openid'])->find();
                        if(!$third){
                            $third_data = [
                                'platform'      =>  $platform,
                                'user_id'       =>  0,
                                'openname'      =>'',
                                'openid'        =>  $data['openid'],
                                'unionid'      =>  $data['unionid'] ?? '',
                                'access_token'  =>  $data['session_key'],
                                'logintime'     =>  time()
                            ];
                            $third = Third::create($third_data);
                        }else{
                            $third_data = [
                                'access_token'  =>  $data['session_key'],
                                'unionid'      =>  $data['unionid'] ?? '',
                                'logintime'     =>  time()
                            ];
                            if($third->user_id>0){
                                $user = \app\common\model\User::get(['id'=>$third->user_id]);
                                if(!$user){
                                    $third_data['user_id'] = 0;
                                }
                            }
                            $third->save($third_data);
                        }
                        if($third->user_id>0){
                            #模拟登陆
                            $this->auth->direct($user->id);
                            $data = ['userinfo' => $this->auth->getUserinfo()];
                            $data['third'] = ['third_id'=>$third->id,'openname'=>$third->openname,'binding'=>1];
                        }else{
                            $data = ['userinfo'=>[]];
                            $data['third'] = ['third_id'=>$third->id,'openname'=>$third->openname,'binding'=>0];
                        }
                        break;
                    case 'wxpublic':
    
                        break;
                }
            }catch (ThrowableError|Exception $e){
                $this->error($e->getMessage());
            }
            $this->success('获取session_key成功',$data);
    
        }
    
        /**
     * 微信公众号授权登录接口
     */
    public function wechat_public_login() {
        // $platform = $this->request->post("platform");
        $platform = 'wechat';
        $code = $this->request->post("code");
        $config = get_addon_config('third');
        if (!$config || !isset($config[$platform])) {
            $this->error(__('Invalid parameters'));
        }
        $app = new \addons\third\library\Application($config);
        //通过code换access_token和绑定会员
        $result = $app->{$platform}->getUserInfo(['code' => $code]);
        if ($result) {
            $loginret = \addons\third\library\Service::connect($platform, $result);
            if ($loginret) {
                $data = [
                    'userinfo'  => $this->auth->getUserinfo(),
                    'thirdinfo' => $result
                ];
                $this->success(__('Logged in successful'), $data);
            }
        }
    }
    
    /**
     * 查找或创建用户
     */
    private function findOrCreateUser($wechatUser) {
        // 1. 根据openid查找用户
        $user = UserModel::where('openid', $wechatUser['openid'])->first();
        
        // 2. 如果用户不存在则创建
        if (!$user) {
            $user = new UserModel();
            $user->openid = $wechatUser['openid'];
            $user->unionid = $wechatUser['unionid'] ?? '';
            $user->nickname = $wechatUser['nickname'];
            $user->avatar = $wechatUser['avatar'];
            $user->gender = $wechatUser['sex'];
            $user->province = $wechatUser['province'];
            $user->city = $wechatUser['city'];
            $user->country = $wechatUser['country'];
            $user->save();
        }
        
        return $user;
    }

    /**
     * @ApiTitle (获取手机号)
     * @ApiParams (name="third_id", type="int", required=true, description="第三方id")
     * @ApiParams (name="code", type="string", required=true, description="code")
     */
    public function get_mobile()
    {
        $param = $this->request->only(['third_id','code','puser_id']);
        $iv = $this->request->param('iv',null,null);
        $encryptedData = $this->request->param('encryptedData',null,null);
        $wechat = new Wechat($this->platform);
        $third = Third::where('id',array_get($param,'third_id'))->find();
        if(!$third) $this->error('未找到third数据',[],40001);
        if($third->user_id>0){
            $user = \app\common\model\User::get($third->user_id);
            if($user){
                $this->auth->direct($third->user_id);
                $third = ['third_id'=>$third->id,'binding'=>1];
                $this->success('手机号已经注册成功',['userinfo'=>$this->auth->getUserinfo(),'third'=>$third]);
            }
        }

        Db::startTrans();
        try {
            //新版本授权
            if($code = array_get($param,'code')){
                $data = $wechat->getPhoneNumber($code);
            }else if($iv && $encryptedData){
                $data = $wechat->wxEncrypted($third['access_token'],$iv,$encryptedData);
            }else{
                Db::rollback();
                throw new Exception("获取手机号参数错误");
            }
            if(!$data){
                Db::rollback();
                throw new Exception("获取手机号失败");
            }
            $user = \app\common\model\User::where('mobile',$data['phoneNumber'])->find();
            if ($user) {
                if ($user->status != 'normal') {
                    Db::rollback();
                    $this->error(__('Account is locked'));
                }
                //如果已经有账号则直接登录
                $ret = $this->auth->direct($user->id);
            } else {
                $user_config = Config::getMyConfig('user');
                $extend = [];
                if(isset($user_config['avatar'])){
                    $extend['avatar'] = cdnurl($user_config['avatar'],true);
                }
                $extend['nickname'] = preg_match("/^1[3-9]{1}\d{9}$/", $data['phoneNumber']) ? substr_replace($data['phoneNumber'], '****', 3, 4) : $data['phoneNumber'];
                $ret = $this->auth->register($data['phoneNumber'], Random::alnum(), '', $data['phoneNumber'], $extend);
            }
            $puser_id = array_get($param,'puser_id');
            if ($ret) {
                $userinfo = $this->auth->getUserinfo();
                #更新third表字段
                $third->user_id = $userinfo['id'];
                $third->save();
                #创建用户消息表
                UserAccount::addAccount($userinfo['id'],$puser_id);
                $third = ['third_id'=>$third->id,'binding'=>1];
                $data = ['userinfo' => $userinfo,'third'=>$third];
            } else {
                Db::rollback();
                $this->error($this->auth->getError());
            }
        }catch (ThrowableError $e){
            Db::rollback();
            $this->error($e->getMessage());
        }catch (Exception $e){
            Db::rollback();
            $this->error($e->getMessage());
        }
        Db::commit();
        $this->success(__('登录成功'), $data);
    }

    /**
     * 网页授权
     */
    public function auth(){
        $target_url = $this->request->param('target_url',null,null);
        if(Cookie::get('token') && $this->auth->getUser()){
            $target = explode('?',$target_url);
            if(count($target) > 1){
                $domain = $target[0];
                $query = $target[1].'&token='.Cookie::get('token');
                $target_url = $domain.'?'.$query;
            }else{
                $target_url .= '?token='.Cookie::get('token');
            }
            header('location:'.$target_url);
        }else{
            Session::set('target_url',$target_url);
            (new Wechat('wxoffical'))->auth();
        }
    }

    /**
     * 网页授权回调
     */
    public function auth_back(){
        (new Wechat('wxoffical'))->auth_back();
    }

    /**
     * 手机验证码登录
     *
     * @ApiMethod (POST)
     * @param string $mobile  手机号
     * @param string $captcha 验证码
     */
    public function mobilelogin()
    {
        $mobile = $this->request->post('mobile');
        $captcha = $this->request->post('code');
        if (!$mobile || !$captcha) {
            $this->error(__('Invalid parameters'));
        }
        if (!Validate::regex($mobile, "^1\d{10}$")) {
            $this->error(__('手机号格式错误'));
        }
        if (!Sms::check($mobile, $captcha, 'mobilelogin')) {
            //$this->error(__('验证码错误'));
        }
        $user = \app\common\model\User::getByMobile($mobile);
        if ($user) {
            if ($user->status != 'normal') {
                $this->error(__('账号已被锁定'));
            }
            //如果已经有账号则直接登录
            $ret = $this->auth->direct($user->id);
        } else {
            $extend['nickname'] = preg_match("/^1[3-9]{1}\d{9}$/", $mobile) ? substr_replace($mobile, '****', 3, 4) : $mobile;
            $ret = $this->auth->register($mobile, Random::alnum(), '', $mobile, $extend);
        }
        $puser_id = $this->request->post('puser_id');
        if ($ret) {
            // Sms::flush($mobile, 'mobilelogin');
            $userinfo = $this->auth->getUserinfo();
            #创建用户账户
            UserAccount::addAccount($userinfo['id'],$puser_id);
            $data = ['userinfo' => $userinfo];
            $this->success(__('Logged in successful'),$data);
        } else {
            $this->error($this->auth->getError());
        }
    }


    /**
     * 用户信息
     */
    public function info(){
        // var_dump($this->auth->getUser());die;
        // $user = $this->auth->getUser()->hidden(['group_id','password','salt','level','bio','token','loginip','joinip','score','jointime','successions','maxsuccessions','prevtime']);
        
         $user = $this->auth->getUser()->hidden(['group_id','password','salt','level','bio','token','loginip','joinip','score','jointime','successions','maxsuccessions','prevtime']);
         
        $account = UserAccount::where('user_id',$user->id)->field('total_money,money,withdraw_money,(user_message+system_message) as total_message,points')->find();
        #积分
        $user->points = $account['points'];
        $user->account = $account;
        $mcn = Db::name('merchant')->where('user_id',$user->id)->where('audit_status',1)->find();
        if ($mcn){
            $user->merchant = 1;
        }else{
            $user->merchant = 0;
        }
        #团队人数
        $user->team_count = UserAccount::with(['user'=>function($q){
                $q->withField(['id','nickname','avatar']);
            }])
            ->where('first_user_id|second_user_id',$this->auth->id)
            ->count();
        #优惠券
        $user->coupon_count = UserCoupon::getCount(['user_id'=>$user->id]);
        #消息
        // var_dump($account)
        $user->user_message = $account['total_message'];
        #我的门店总余额
        $user->money = $account->money;
        //  $user->total_shop_money = $user->money;
        #核销权限
        $user->verifier_status = ShopVerifier::isVerifier($user->mobile);
        #套餐
        $user->package_count = UserPackage::where("user_id",$user->id)->count();
        //待服务
        $user->unuse_order_count = \app\common\model\xiluxc\order\Order::getCount('unuse',$user->id);
        $user->uncomment_order_count = \app\common\model\xiluxc\order\Order::getCount('uncomment',$user->id);
        $user->finished_order_count = \app\common\model\xiluxc\order\Order::getCount('finished',$user->id);
        
        $user->first_free = 0;
        $user->vip_discount = 0;
        
        $vip = Shopvip::where('id', $user->level)->find();
        if ($vip) {
            $year = getYearDifference($user->viptime);
            $money_log = Db::name('xiluxc_money_log')->where('user_id', $user->id)->where('type', 3)->find();
            if ($vip->first_free == 1 && empty($money_log)) {
                $user->first_free = 1;
            }
            if ($vip->first_discount > 0 && empty($money_log)) {
                $user->vip_discount = $vip->first_discount;
            } else {
                if ($year < 1) {
                    $user->vip_discount = $vip->first_year_discount;
                } else if ($year == 1) {
                    $user->vip_discount = $vip->second_year_discount;
                } else {
                    $user->vip_discount = $vip->perpetual_discount;
                }
            }
        }
        
        $user->vip = $vip;
        
        //加密
        $user['mobile'] = substr_replace($user['mobile'],'****',3,4);
        $this->success('查询成功',$user);
    }

    /**
     * @ApiTitle (修改会员个人信息)
     * @ApiRoute (/api/xilumarket.user/profile)
     * @ApiMethod (POST)
     * @ApiHeaders (name=token, type=string, require=true, description="Token")
     * @ApiParams (name="avatar", type="string", required=true, description="头像")
     * @ApiParams (name="nickname", type="string", required=true, description="昵称")
     */
    public function profile()
    {
        $user = $this->auth->getUser();
        $user->visible(['bio','avatar','nickname','mobile','gender']);
        if($this->request->isPost()) {
            $nickname = $this->request->post('nickname');
            $avatar = $this->request->post('avatar', '', 'trim,strip_tags,htmlspecialchars');
            $gender = $this->request->post('gender', '');
            $user->nickname = $nickname;
            $user->avatar = $avatar;
            $user->gender = $gender;
            $user->allowField(['avatar','nickname','gender'])->save();

            $this->success('', $user);
        }
        $this->success('',$user);
    }

    /**
     * 品牌入驻
     * @throws Exception
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function brand_auth(){
        $params = $this->request->post('');
        $userBrandValidate = new UserBrand();
        if(!$userBrandValidate->check($params)){
            $this->error($userBrandValidate->getError());
        }
        $user = \app\common\model\User::where('mobile',$params['account_mobile'])->find();
        if($user){
           $xiluxcUser = BrandUser::where("user_id",$user['id'])->find();
           if($xiluxcUser){
               $this->error("当前账号已存在门店信息");
           }
        }
        if(!$user){
            $userBrand = \app\common\model\xiluxc\brand\UserBrand::where("account_mobile",$params['account_mobile'])->whereIn('status',['checked','passed'])->count();
            if($userBrand){
                $this->error("当前账号已有审核或通过的申请信息");
            }
        }
        try {
            $ret  = \app\common\model\xiluxc\brand\UserBrand::create(array_merge([
                'user_id'               =>  $this->auth->id,
                'status'          =>  'checked',
                'weigh'             =>  0,
            ],$params));
        }catch (Exception|PDOException $e){
            $this->error($e->getMessage());
        }

        $this->success(__('提交成功'));
    }

    /**
     * 门店入驻
     * @throws Exception
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function shop_auth(){
        $params = $this->request->post('');
        $userBrandValidate = new \app\common\validate\xiluxc\brand\Shop();
        if(!$userBrandValidate->check($params)){
            $this->error($userBrandValidate->getError());
        }
        $user = $this->auth->getUser();
        if(ShopBrand::where("user_id",$user->id)->find()){
            $this->error("您的账号已是品牌账号，不可申请");
        }
        $shop = Shop::get(['user_id'=>$user['id']]);
        if($shop && in_array($shop->audit_status,['checked','passed'])){
            $this->error("您的账号已存在门店信息");
        }
        if($params['address']){
            $result = xiluxcGetAddr($params['lat'],$params['lng']);
  
            //$result = xiluxcGetGeo($params['address']);
            if($result){
                $params['province_id'] = Area::getIdByName($result['prov'],1,0);
                $params['city_id'] = Area::getIdByName($result['city'],2,$params['province_id']);
                $params['district_id'] = Area::getIdByName($result['district'],3,$params['city_id']);
            }else{
                // $this->error("请检查地图配置");
            }
        }
        Db::startTrans();
        try {
            //单店
            BrandUser::saveInfo(1,$user);
            $params['user_id'] = $user->id;
            $params['audit_status'] = "checked";
            $params['weigh'] = 0;
            //创建门店
            if($shop){
                $shop->allowField(true)->save($params);
            }else{
                $shopModel = new Shop();
                $result = $shopModel->allowField(true)->save($params);
                $shop = $shopModel;
            }
            //创建门店钱包
            ShopAccount::addAccount($shop,$params);
            //属性
            if($propertyIds = array_get($params,'property_ids')){
                ShopProperty::setData($shop,$propertyIds);
            }
            //服务
            if($serviceIds = array_get($params,'service_ids')){
                ShopService::setData($shop,$propertyIds);
            }
        }catch (Exception|PDOException $e){
            Db::rollback();
            $this->error($e->getMessage());
        }
        Db::commit();

        $this->success(__('提交成功，请耐心等待审核结果'));
    }

    //商户注册
        public function shopsh_auth(){
        $params = $this->request->post('');
            $user = $this->auth->getUser();
//        dump($params);die();
         $merchant = Db::name('merchant')->where('user_id',$user->id)->where('audit_status',0)->find();
         if($merchant){
             $this->error("请等待审核");
         }
         $merchant2 = Db::name('merchant')->where('user_id',$user->id)->where('audit_status',1)->find();
         if($merchant2){
             $this->error("你已入驻了商户");
         }
//         dump($merchant2);die();
            Db::startTrans();
         try {
             $data = [
                 'user_id' => $user->id,
                 'merchant_name' => $params['name'],
                 'merchant_logo' => $params['images'],
                 'contact_name' => $params['connector'],
                 'contact_phone' => $params['concat_mobile'],
                 'business_license' => $params['license_image'],
                 'audit_status' => 0,
                 'createtime' => time(),
              ];
          $mec = Db::name('merchant')->insert($data);
         }catch (Exception|PDOException $e){
             Db::rollback();
             $this->error($e->getMessage());
         }
         Db::commit();
         $this->success(__('提交成功，请耐心等待审核结果'));

        }


    /**
     * 用户钱包
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function account(){
        $userId = $this->auth->id;
        $account = UserAccount::field("id,user_id,money,total_money,withdraw_money")->where('user_id',$userId)->find();
        $freezeMoney = Divide::where('first_user_id',$userId)->where('status',1)->sum('first_money');
        $freezeMoney2 = Divide::where('second_user_id',$userId)->where('status',1)->sum('second_money');
        $account->freeze_money  = bcadd($freezeMoney,$freezeMoney2,2);
        $this->success('',$account);
    }

    /**
     * 投诉建议列表
     */
    public function myadvice(){
        $params = $this->request->param("");
        $pagesize = array_get($params,'pagesize',10);
        $advice = new Advice();
        $lists = $advice->where("user_id",$this->auth->id)
            ->order("id","desc")
            ->paginate($pagesize)
            ->each(function ($row){
                $row->append(['images_text','createtime_text','replytime_text']);
            });
        $this->success("提交成功",$lists);
    }

    /**
     * 投诉建议
     */
    public function advice(){
        $params = $this->request->post("");
        Db::startTrans();
        try {
            $images = array_get($params,'images');
            $params['images'] = $images? (is_array($images) ? implode(',',$images) : $images) :'';
            $params['status'] = 'normal';
            $params['user_id'] = $this->auth->id;
            $advice = new Advice();
            $ret = $advice->allowField(true)->save($params);
        }catch (Exception|PDOException $e) {
            Db::rollback();
            $this->error($e->getMessage());
        }
        Db::commit();
        $this->success("提交成功");
    }

    /**
     * 我的门店余额列表
     */
    public function my_shop_account(){
        // $model = new UserShopAccount;
        // $shop = $model::with(['shop'=>function($q){
        //     $q->withField(['id','name','image','address','lat','lng']);
        // },'brand'=>function($q){
        //     $q->withField(['id','brand_name','logo']);
        // }
        //     ])
        //     ->where($model->getTable().".user_id",$this->auth->id)
        //     ->order("updatetime",'desc')
        //     ->paginate(request()->param('pagesize',10))
        //     ->each(function ($row){
        //         $row->shop->append(['image_text']);
        //     });
        // 查询用户及资金记录（带分页）
        $pernum = 20;
        $pagenum = input('get.pagenum/d');
        // var_dump($this->auth->id);die;
        //   $where['u.id']=7;
        $list = Db::name('user_money_log')
            ->where('user_id', $this->auth->id)
            ->order("createtime desc")
            ->page($pagenum, $pernum)
            ->select();
    // dump($list);die;
        $this->success('',$list);
    }

    /**
     * 我的门店余额
     */
    public function shop_account(){
        if($this->request->isPost()){
            $shopId = $this->request->post("shop_id");
            $shop = new Shop();
            $shop = $shopId ? $shop->normal()->passed()->field("id,name,type,image,brand_id")->where("id",$shopId)->find() : null;
            if(!$shop){
                $this->error("门店不存在或已下架");
            }
            $shop->append(['image_text']);
            try {
                $userShopAccount = UserShopAccount::addAccount($this->auth->id,$shopId,false);
            }catch (Exception|PDOException $e){
                $this->error($e->getMessage());
            }
            $brand = $shop['type'] == 2 ? ShopBrand::get(['user_id'=>$shop->brand_id]) : null;
            $this->success('',['shop'=>$shop,'brand'=>$brand,'account'=>$userShopAccount]);
        }
        $this->error("非法请求");
    }

    /**
     * 我的团队
     * @throws \think\exception\DbException
     */
    public function myteam(){
        $params = $this->request->param('');
        $pagesize = array_get($params,'pagesize');
        $userId = $this->auth->id;
        $lists = UserAccount::field("id,user_id,first_user_id,second_user_id,bindtime")
            ->with(['user'=>function($q){
            $q->withField(['id','nickname','avatar']);
        }])
            ->where('first_user_id|second_user_id', $userId)
            ->order('bindtime','desc')
            ->paginate($pagesize)
            ->each(function ($row) use($userId){
                $row->bindtime_text = datetime($row->bindtime,"Y-m-d H:i");
                $money = Divide::where("first_user_id",$userId)->where("user_id",$row->user->id)->where('status',3)->sum("first_money");
                $money2 = Divide::where("second_user_id",$userId)->where("user_id",$row->user->id)->where('status',3)->sum("second_money");
                $row->total_money = bcadd($money,$money2,2);
            });
        $this->success('',$lists);
    }

    /**
     * 积分日志
     */
    public function score_log(){
        $params = $this->request->param('');
        $pagesize = array_get($params,'pagesize');
        $where['user_id'] = $this->auth->id;
        $lists = UserScoreLog::where($where)
            ->order('id','desc')
            ->paginate($pagesize)
            ->each(function ($row){
                $row->score_abs = abs($row->score);
                $row->createtime_text = datetime($row->createtime,"Y.m.d H:i");
            });
        $this->success('查询成功',$lists);
    }

    /**
     * 佣金日志
     */
    public function money_log(){
        $params = $this->request->param('');
        $pagesize = array_get($params,'pagesize');
        $where['user_id'] = $this->auth->id;
        if($type = array_get($params,'type')){
            $where['type'] = $type;
        }else{
            $this->error("参数错误");
        }
        if($type == 1){
            //余额
            $where['shop_id'] = array_get($params,'shop_id');
        }
        $lists = MoneyLog::where($where)
            ->order('id','desc')
            ->paginate($pagesize)
            ->each(function ($row){
                $row->money_abs = abs($row->money);
                $row->extra_text = json_decode($row->extra,true);
                $row->createtime_text = datetime($row->createtime,"Y.m.d H:i");
                if(isset($row->extra_text['user_id'])){
                    $row->buyer = \app\common\model\User::field("id,nickname,avatar")->where('id',$row->extra_text['user_id'])->find();
                }else{
                    $row->buyer = null;
                }
            });
        $this->success('查询成功',$lists);
    }

    /**
     * 提现申请
     */
    public function withdraw()
    {
        $params = $this->request->post('');
        try {
            $result = Withdraw::withdraw($params, $this->auth->getUser());
        } catch (Exception $e) {
            $this->error($e->getMessage());
        }
        $this->success('提现成功', $result);
    }

    /**
     * 提现记录
     */
    public function withdraw_log(){
        $params = $this->request->param('');
        $pagesize = array_get($params,'pagesize');
        $lists = Withdraw::where('user_id',$this->auth->id)
            ->order('id','desc')
            ->paginate($pagesize);
        $this->success('查询成功',$lists);
    }

    /**
     * 海报
     */
    public function poster(){
        $uid = $this->auth->id;

        $page = "pages/index/index";
        if($this->platform == 'wxmini'){
            $wechat = new Wechat($this->platform);
            $res = $wechat->getUnlimited("uid=".$uid,$page);
            if(!$res) $this->error('获取小程序二维码失败');
            $path = "/runtime/xiluxc/";
            if (!file_exists(ROOT_PATH . $path)) {
                @mkdir(ROOT_PATH . $path, 0777, true);
            }
            $filename = $uid.'.png';
            $qrcode = $path.$filename;
            file_put_contents(ROOT_PATH.$qrcode,$res);

            // 上传成功后该文件将被删除，请务必使用临时文件，这里$tempFile为你服务器准备上传的文件
            $tempFile = ROOT_PATH . $qrcode;
            $qrcode2 = (new Upload())->uploadApi($tempFile);
        }else{
            $qrcode2 = request()->domain().'/web/'.$page."?uid=".$uid;
        }

        $shareConfig = Config::getMyConfig('share');
        $this->success('',[
            'nickname'      => $this->auth->nickname,
            'copywriting'   => $shareConfig['poster_text'],
            'poster_img'    => cdnurl($shareConfig['poster_image'],true),
            'avatar'          => cdnurl($this->auth->avatar,true),
            'qrcode'          => $qrcode2 ?? '',
        ]);
    }


}